INSERT INTO APPLICATION_USER (APPL_USER_ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, IS_LOCKED, CREATED_DATE, LAST_MODIFIED_DATE, IS_DELETED) VALUES ('admin', 'admin', 'admin', 'Phuong', 'Nguyen', 'nhphuong96@gmail.com' ,0, '01-01-2019', '12-31-9999', 0);

INSERT INTO APPLICATION_ROLE (APPL_ROLE_ID, CREATED_DATE, LAST_MODIFIED_DATE, IS_DELETED) VALUES ('ADMIN', '01-01-2019', '12-31-9999', 0);
INSERT INTO APPLICATION_ROLE (APPL_ROLE_ID, CREATED_DATE, LAST_MODIFIED_DATE, IS_DELETED) VALUES ('USER', '01-01-2019', '12-31-9999', 0);

INSERT INTO APPLICATION_USER_ROLE(APPL_USER_KEY, APPL_ROLE_KEY) VALUES ((SELECT APPL_USER_KEY FROM APPLICATION_USER WHERE APPL_USER_ID = 'admin'), (SELECT APPL_ROLE_KEY FROM APPLICATION_ROLE WHERE APPL_ROLE_ID = 'ADMIN'));